on: [push]
name: Linux-container

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build
      run: |
        LOCAL_IMAGE_ID=craig2text:0.0.${{ github.run_number }}
        REMOTE_IMAGE_ID=ghcr.io/${{ github.actor }}/$LOCAL_IMAGE_ID
        docker build . --tag $LOCAL_IMAGE_ID
        docker tag $LOCAL_IMAGE_ID $REMOTE_IMAGE_ID
        docker push $REMOTE_IMAGE_ID
    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
    - name: List Azure container jobs (test)
      run: |
        dotnet tool install -g namespace2xml
        namespace2xml -i azure-job.yaml -v properties.template.containers.0.image=ghcr.io/stop-cran/craig2text:0.0.${{ github.run_number }} identity.tenantId=${{ secrets.TENANT_ID }} environmentId=/subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.App/managedEnvironments/craigrec2telegram-1 -s azure-job-schema.yaml
        az containerapp job update --name craig2text-job --resource-group ${{ secrets.RESOURCE_GROUP }} --yaml azure-job-parametrized.yaml -o table
